Badges
pavel-sazonov/test-guru pull request #19
Opened 2018-02-20 17:22 UTC by pavel-sazonov

2018-02-20 17:25 UTC, pavel-sazonov commented on app/controllers/test_passages_controller.rb
Много повторов кода получилось.
Но никак не придумаю, как можно этого избежать, так как могут выполняться сразу несколько условий.

2018-02-20 17:27 UTC, pavel-sazonov commented on app/controllers/test_passages_controller.rb
> +
Бейдж за первый пройденный тест.
Второе условие, что это должен быть единственный тест.

2018-02-20 17:29 UTC, pavel-sazonov commented on app/controllers/test_passages_controller.rb
> +
Бейдж за первый правильный тест.
Второе условие, чтобы такой тест был единственным. Чтобы за следующий пройденный тест этот бейдж не назначался.

2018-02-20 17:57 UTC, psylone requested changes

2018-02-20 17:57 UTC, psylone commented on app/controllers/test_passages_controller.rb
Все довольно просто: нужна отдельная абстракция которая станет выдавать бэйджи. Это бизнес-логика, в контроллере ее быть не должно. А по хорошему, не должно быть и в модели.

2018-02-20 17:57 UTC, psylone commented on app/models/user.rb
> +  end
Отдельный метод для тестов конкретной категории? За это должно отвечать правило выдачи бэйджа.

2018-02-20 17:57 UTC, psylone commented on db/schema.rb
> +    t.string "body"
Смысл правила выдачи бэйджа в том чтобы это правило рассказывало о том когда нужно выдавать бэйдж. То есть, например, если бэйдж выдается за успешное прохождение тестов из какой-то категории, то в правиле должен быть атрибут в котором будет название этой категории.

Если бэйдж выдается за прохождение всех тестов определенного уровня, в атрибуте правило должно храниться значение этого уровня.

Логика в коде не должна ничего знать о значениях правила. Значения хранятся в правиле. Но логика кода может знать о том к какому типу относится правило и как его следует интерпретировать. Иными словами, если у нас 3 различных типа правила, например, на уровень, категорию и, скажем, первое прохождение, то должно быть 3 метода которые описывают поведение. Но при этом мы можем задать 2 правила на уровень одно из которых будет выдавать бэйдж после прохождения тестов 1-го уровня, а другое - 2-го, но при этом за выдачу будет отвечать один и тот же метод.

2018-03-13 10:09 UTC, pavel-sazonov commented on app/services/award_with_badges.rb
> +    if @test_passage.test.category.title == category
тут условие, чтобы, если пройти все тесты этой категории и потом пройти тест из другой категории, бейдж не присваивался повторно

2018-03-13 10:11 UTC, pavel-sazonov commented on app/controllers/test_passages_controller.rb
> +    AwardWithBadges.new(@test_passage).call if @test_passage.correct?
Не смог придумать, к чему здесь можно привязать создание флеш-сообщения об успешном присваивании бейджа?

2018-03-13 22:46 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    AwardWithBadges.new(@test_passage).call if @test_passage.correct?
Можно считать количество бэйджей которое было и стало.

2018-03-13 22:47 UTC, psylone approved these changes

2018-03-16 07:17 UTC, merged